BACKGROUNDS = [
               "cat1.jpg",
               "cat2.jpg",
               "cat3.jpg",
               "cat4.jpg",
               "cat5.jpg",
               "cat6.jpg",
               "cat7.jpg",
               "cat8.jpg",
               "cat9.jpg",
               "cat10.jpg",
               "cat11.jpg",
               "cat12.jpg",
               "cat13.jpg",
               "cat14.jpg",
               "cat15.jpg",
               "cat16.jpg",
               "cat17.jpg",
               "cat18.jpg",
               "cat19.jpg",
               "cat20.jpg"
              //  "wood.jpg",
              //  "window.jpg",
              //  "cloak.png",
              //  "wall.jpg",
              //  "tile.gif",
              //  "tapestry",
              //  "stone",
              //  "gold",
              //  "wood-panels",
              //  "stone2",
              //  "versailles",
              //  "ceiling",
              //  "stained-glass",
              //  "window2",
              //  "white-fabric",
              //  "magic",
              //  "flower-frame",
              //  "canvas",
              //  "tile2",
              //  "rust",
              //  "parchment3",
              //  "writing",
              //  "metal-wall",
              //  "berries",
              //  "rug",
              //  "filigree",
              //  "flower-page",
              //  "checkers"
            ];

module.exports = BACKGROUNDS;
